### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by elliotlings** [plimble/clover#1]
Hi there, great package.

I'm new to Go.
What would be the best way to extend this to support PostgreSQL?

**Comment by witooh** [comment]
You can see the example in store folder. You have to implement store. The minimal store you should have implement is AuthServerStore

This  is all of Store interface
```go
type AuthServerStore interface {
	GetClient(id string) (Client, error)
	SetAccessToken(accessToken *AccessToken) error
	GetAccessToken(at string) (*AccessToken, error)
}

type UserStore interface {
	GetUser(username, password string) (string, []string, error)
}

type RefreshTokenStore interface {
	RemoveRefreshToken(rt string) error
	SetRefreshToken(rt *RefreshToken) error
	GetRefreshToken(rt string) (*RefreshToken, error)
}

type AuthCodeStore interface {
	SetAuthorizeCode(ac *AuthorizeCode) error
	GetAuthorizeCode(code string) (*AuthorizeCode, error)
}

type PublicKeyStore interface {
	GetKey(clientID string) (*PublicKey, error)
}
```

UserStore for Password Grant Type
RefreshTokenStore for enable refresh token in Password and Code Grant type
AuthCodeStore for enable Authenticate Response type code and Code Grant type
PublicKeyStore for enable JWT Accesstoken
